export const SEARCH_FILED_CHANGE='SEARCH_FILED_CHANGE';

export const FETCH_ROBOTS_PENDING='FETCH_ROBOTS_PENDING';

export const FETCH_ROBOTS_FULLFILLED='FETCH_ROBOTS_FULLFILLED';

export const FETCH_ROBOTS_ERROR='FETCH_ROBOTS_ERROR';